sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-nanjing.aliyuncs.com
    access-key-id: *
    access-key-secret: *
    bucket-name: *
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  wechat:
    appid: *
    secret: *
    mchid: *
    mchSerialNo: *
    privateKeyFilePath: *
    apiV3Key: *
    weChatPayCertFilePat: *
    notifyUrl: *
    refundNotifyUrl: *
  shop:
    address: 江苏科技大学（长山校区）
    shop-coordinate: 32.111581,119.363188
  baidu:
    ak: *